import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useLayoutEffect, useRef, useEffect } from "react";
import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

import Link from "next/link";
import Layout from "@/components/Layout";
import Hero from "@/components/Hero";
import Projects from "@/components/Projects";
import Experience from "@/components/Experience";
import { Bg3Component } from "@/components/Icons";
import Skills from "@/components/Skils";
import Contact from "@/components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Layout>
          <Hero />
          <Projects />
          <div className=" h-64">&nbsp;</div>
          <Experience />
          <div className="flex justify-center items-center content-center pt-4">
            <Bg3Component />
          </div>
          <Skills />
          <div className="flex justify-center items-center content-center pt-16">
            <Bg3Component />
          </div>
          <Contact />
        </Layout>
      </main>
    </>
  );
}
