import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useLayoutEffect, useRef, useEffect } from "react";
import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    var width = document.querySelector(".horizontal-container").offsetWidth;

    console.log(width);

    gsap.registerPlugin(ScrollTrigger);

    var rotateOnHero = gsap.to("#green", {
      rotation: 280,
      ease: "none",
      scrollTrigger: {
        trigger: ".hero",
        // pin: true,
        scrub: 1,
        markers: false,
        start: "top top",
        end: () => "+=" + width,
      },
    });

    let sections = gsap.utils.toArray(".panel");

    let scrollTween = gsap.to(sections, {
      xPercent: -100 * (sections.length - 1),
      ease: "none", // <-- IMPORTANT!
      scrollTrigger: {
        trigger: ".horizontal-container",
        pin: true,
        scrub: 1,
        // snap: directionalSnap(1 / (sections.length - 1)),
        invalidateOnRefresh: true,
        snap: 1 / (sections.length - 1),
        end: () =>
          "+=" + document.querySelector(".horizontal-container").offsetWidth,
      },
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="nav-container fixed top-0 w-full z-10 ">
          <div className="nav flex justify-end ">
            <Link className="uppercase font-bold text-2xl  p-4" href="/contact">
              contact me
            </Link>
          </div>
        </div>
        <div className="horizontal-container">
          <div className=" panel hero  h-screen pt-12 w-screen">
            <div className="hero-title-container">
              <div className="hero-title-row-container  flex justify-center ">
                <div className="hero-title-row flex gap-4 w-1/2 mt-5 mb-5">
                  <div className="grow title-rectangle"></div>
                  <div className=" hero-small-title uppercase font-bold">
                    a message from earth
                  </div>
                </div>
              </div>
              <div className="hero-title-row-container  flex justify-center ">
                <div className="hero-title-row hero-title uppercase text-5xl font-bold">
                  hello fellow galaxy member
                </div>
              </div>
              <div className="hero-title-row-container  flex justify-center ">
                <div className="hero-title-row flex gap-4 w-1/2 mt-5 mb-5">
                  <div className=" hero-small-title uppercase font-bold">
                    a message from earth
                  </div>
                  <div className="grow  title-rectangle"></div>
                </div>
              </div>
            </div>

            <div className="hero-content-container flex">
              <div className="hero-content-column">
                <div className="social-links-container">
                  <ul className="social-links pt-5">
                    <li className="social-link p-3">
                      <Image
                        src="/github.png"
                        width={40}
                        height={40}
                        alt="Picture of the author"
                      />
                    </li>
                    <li className="social-link  p-3">
                      <Image
                        src="/inst.png"
                        width={40}
                        height={40}
                        alt="Picture of the author"
                      />
                    </li>
                    <li className="social-link  p-3">
                      <Image
                        src="/linkin.png"
                        width={40}
                        height={40}
                        alt="Picture of the author"
                      />
                    </li>
                  </ul>
                </div>
              </div>
              <div className="hero-content-column flex gap-12 flex-col grow justify-center">
                <div className="hero-identifier text-5xl font-bold text-center">
                  I am Karim
                </div>
                <div className="hero-more-info-box flex justify-center text-5xl font-bold text-center">
                  <div className="hero-more-info-text m-10">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    click to open
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className=" panel skills-container grid h-screen place-items-center w-screen"></div>
          <div className=" panel projects-container grid h-screen place-items-center w-screen"></div>
          <div className=" panel experiences-container grid h-screen place-items-center w-screen"></div>
        </div>

        <div
          id="wrap"
          className="grid w-screen place-items-center fixed top-1/2"
        >
          <div id="green" className="">
            <Image
              src="/globe.png"
              width={1300}
              height={1300}
              alt="Picture of the author"
            />
          </div>
        </div>

        <div className="fixed bottom-2 flex w-screen pl-9 pr-9">
          <div className=" grow">
            <Image
              src="/enter.png"
              width={60}
              height={60}
              alt="Picture of the author"
            />
          </div>
          <div className=" grow grid justify-items-end">
            <Image
              src="/scroll.png"
              width={60}
              height={60}
              alt="Picture of the author"
            />
          </div>
        </div>
      </main>
    </>
  );
}
